name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y --no-progress
          choco install ninja -y --no-progress
          choco install curl -y --no-progress

      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Wikitenaur-Windows
          path: build/main.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          brew update
          brew install--formula cmake

      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Wikitenaur-macOS
          path: build/main