name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install make mingw -y --no-progress

      - name: Download curl.h and dependencies
        run: |
          curl -L -o curl.zip https://curl.se/windows/dl-8.13.0_2/curl-8.13.0_2-win64-mingw.zip
          Expand-Archive curl.zip D:/a/Wikitenaur-Image-Downloader/Wikitenaur-Image-Downloader/
          ren curl-8.13.0_2-win64-mingw curl
          ls -R
        

      - name: Set up environment variables
        run: |
          setx PATH "%PATH%;C:/Program Files/mingw-w64/bin"

      - name: Build with Makefile
        run: |
          make -f Makefile

      - name: Debug build directory
        run: dir build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-Windows
          path: build/main.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          brew update
          brew install --formula cmake curl

      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-macOS
          path: build/main

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ libcurl4-openssl-dev pkg-config

      - name: Configure
        run: cmake -S . -B build -G "Ninja" -DCMAKE_USE_PKGCONFIG=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-Linux
          path: build/main