name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: dir build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-Windows
          path: build/main.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          brew update
          brew install --formula cmake curl

      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-macOS
          path: build/main

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ libcurl4-openssl-dev pkg-config

      - name: Configure
        run: cmake -S . -B build -G "Ninja" -DCMAKE_USE_PKGCONFIG=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: main-Linux
          path: build/main