name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up dependencies
      - name: Set up dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install ninja -y

      # Configure the project with CMake
      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      # Build the project
      - name: Build
        run: cmake --build build --config Release

      # Upload the executable as an artifact
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: Wikitenaur-Windows
          path: build/*