name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install ninja -y

      - name: Configure
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Debug build directory
        run: ls -R build

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Wikitenaur-Windows
          path: build/main.exe